[tox]
envlist = flake8, pytest
isolated_build = true

[testenv:flake8]
deps = flake8
commands = flake8 src/stemforge tests

[testenv:pytest]
extras =
deps =
    pytest
    pytest-mock
commands = pytest {posargs}
