[tox]
envlist = flake8, black, pytest
isolated_build = true

[testenv:flake8]
deps = flake8
commands = flake8 src/stemforge tests

[testenv:black]
deps = black
commands = black --check src/stemforge tests

[testenv:pytest]
extras =
deps =
    pytest
    pytest-mock
commands = pytest {posargs}
