[tox]
envlist = lint, pytest
isolated_build = true

[testenv:lint]
deps =
    flake8
    black
commands =
    black --check src/stemforge tests
    flake8 src/stemforge tests

[testenv:pytest]
extras =
deps =
    pytest
    pytest-mock
commands = pytest {posargs}
